# Generated by Django 5.0.1 on 2024-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="telephone_mere",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
