# Generated by Django 5.0.1 on 2024-02-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_etudiant_telephone_mere"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("personnelid", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "M"), ("F", "F")], default="M", max_length=5
                    ),
                ),
                ("telephone", models.IntegerField(blank=True, null=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("multimedia", "multimedia"),
                            ("cheick", "cheick"),
                            ("administration", "administration"),
                            ("rvs", "rvs"),
                        ],
                        default="multimedia",
                        max_length=50,
                    ),
                ),
                ("travail", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=50)),
            ],
        ),
    ]
