# Generated by Django 5.0.1 on 2024-02-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_personnel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
