# Generated by Django 5.0.1 on 2024-02-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_personnel_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="centre",
            field=models.CharField(
                choices=[("Antananarivo", "Antananarivo"), ("Manakara", "Manakara")],
                default="Antananarivo",
                max_length=20,
            ),
        ),
    ]
