# Generated by Django 5.0.1 on 2024-02-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_personnel_centre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jamat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("jamatid", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "M"), ("F", "F")], default="M", max_length=5
                    ),
                ),
                ("telephone", models.IntegerField(blank=True, null=True)),
                ("age", models.IntegerField()),
                (
                    "centre",
                    models.CharField(
                        choices=[
                            ("Antananarivo", "Antananarivo"),
                            ("Manakara", "Manakara"),
                        ],
                        default="Antananarivo",
                        max_length=20,
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
