# Generated by Django 5.0.1 on 2024-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_jamat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Madrassah",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("madrassahid", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "M"), ("F", "F")], default="M", max_length=5
                    ),
                ),
                ("telephone", models.IntegerField(blank=True, null=True)),
                ("adress", models.CharField(max_length=100)),
                (
                    "centre",
                    models.CharField(
                        choices=[
                            ("Antananarivo", "Antananarivo"),
                            ("Manakara", "Manakara"),
                        ],
                        default="Antananarivo",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jamat",
            name="adress",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
