# Generated by Django 5.0.1 on 2024-02-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_madrassah_jamat_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="madrassah",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
