# Generated by Django 5.0.1 on 2024-02-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_madrassah_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="jamat",
            name="imageprofile",
            field=models.ImageField(
                blank=True, default="images/avatar.jpg", null=True, upload_to="images/"
            ),
        ),
        migrations.AddField(
            model_name="madrassah",
            name="imageprofile",
            field=models.ImageField(
                blank=True, default="images/avatar.jpg", null=True, upload_to="images/"
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="imageprofile",
            field=models.ImageField(
                blank=True, default="images/avatar.jpg", null=True, upload_to="images/"
            ),
        ),
    ]
