# Generated by Django 5.0.1 on 2024-02-14 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_jamat_imageprofile_madrassah_imageprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("semestre", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.CharField(max_length=10)),
                ("moyen", models.IntegerField()),
                (
                    "imageprofile",
                    models.ImageField(
                        blank=True,
                        default="images/avatar.jpg",
                        null=True,
                        upload_to="notes/",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("Pass", "Pass"), ("Not Pass", "Not Pass")],
                        default="Pass",
                        max_length=100,
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.etudiant"
                    ),
                ),
            ],
        ),
    ]
