# Generated by Django 5.0.1 on 2024-02-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
