# Generated by Django 4.1.1 on 2024-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_notes_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="etudiantid",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
