# Generated by Django 4.1.1 on 2024-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_etudiant_etudiantid"),
    ]

    operations = [
        migrations.RemoveField(model_name="notes", name="etudiant",),
        migrations.AddField(
            model_name="notes",
            name="etudiantid",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
