# Generated by Django 5.0.1 on 2024-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_remove_notes_etudiant_notes_etudiantid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="etudiantid",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
