# Generated by Django 5.0.1 on 2024-02-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_notes_etudiantid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Averissement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("etudiantid", models.CharField(max_length=100, null=True)),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField(null=True)),
                ("raison", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("etudiantid", models.CharField(max_length=100, null=True)),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField(null=True)),
                (
                    "swalat",
                    models.CharField(
                        choices=[("Fajr", "Fajr"), ("Maghrib", "Maghrib")],
                        default="Fajr",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
