# Generated by Django 5.0.1 on 2024-02-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_averissement_presence"),
    ]

    operations = [
        migrations.AddField(
            model_name="presence",
            name="presence",
            field=models.CharField(
                choices=[("P", "P"), ("A", "A")], default="Fajr", max_length=10
            ),
        ),
    ]
