# Generated by Django 5.0.1 on 2024-02-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_presence_presence"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imageprofile",
                    models.ImageField(
                        blank=True,
                        default="images/avatar.jpg",
                        null=True,
                        upload_to="images/",
                    ),
                ),
            ],
        ),
    ]
