# Generated by Django 5.0.1 on 2024-02-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_imageupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierUpload",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("etudiantid", models.CharField(max_length=100, unique=True)),
                (
                    "namefile",
                    models.CharField(
                        choices=[
                            ("Residence", "Residence"),
                            ("dece", "Certificace de Dece"),
                            ("tutor", "Tutor ou parent Certification"),
                            ("card identite", "Carte d'identite"),
                            ("copie", "Copie"),
                        ],
                        default="Residence",
                        max_length=50,
                    ),
                ),
                ("file", models.ImageField(upload_to="dossier/")),
            ],
        ),
    ]
