# Generated by Django 5.0.1 on 2024-02-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_dossierupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierupload",
            name="file",
            field=models.FileField(upload_to="dossier/"),
        ),
    ]
