# Generated by Django 5.0.1 on 2024-02-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_dossierupload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierupload",
            name="etudiantid",
            field=models.CharField(max_length=100),
        ),
    ]
