# Generated by Django 5.0.1 on 2024-03-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_dossierupload_etudiantid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="semestre",
            field=models.CharField(
                blank=True,
                choices=[("S1", "S1"), ("S2", "S2"), ("S3", "S3")],
                default="S1",
                max_length=10,
                null=True,
            ),
        ),
    ]
