# Generated by Django 4.1.1 on 2024-03-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_notesupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="date_entre",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="date_sortie",
            field=models.DateField(blank=True, null=True),
        ),
    ]
