# Generated by Django 5.0.1 on 2024-03-11 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_notesupload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="images/avatar.jpg",
                        null=True,
                        upload_to="profile_images/",
                    ),
                ),
                ("telephone", models.IntegerField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("multimedia", "multimedia"),
                            ("cheick", "cheick"),
                            ("administration", "administration"),
                            ("rvs", "rvs"),
                        ],
                        default="multimedia",
                        max_length=50,
                    ),
                ),
                (
                    "centre",
                    models.CharField(
                        choices=[
                            ("Antananarivo", "Antananarivo"),
                            ("Manakara", "Manakara"),
                        ],
                        default="Antananarivo",
                        max_length=20,
                    ),
                ),
                ("job", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
