# Generated by Django 4.1.1 on 2024-03-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_etudiant_date_entre_etudiant_date_sortie"),
    ]

    operations = [
        migrations.AddField(
            model_name="jamat",
            name="job",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
