# Generated by Django 4.1.1 on 2024-03-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_jamat_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="sex",
            field=models.CharField(
                choices=[("M", "M"), ("F", "F")], default="M", max_length=4
            ),
        ),
    ]
