# Generated by Django 5.0.1 on 2024-03-11 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_profile"),
        ("main", "0025_alter_etudiant_sex"),
    ]

    operations = []
