# Generated by Django 5.0.1 on 2024-04-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_merge_0023_profile_0025_alter_etudiant_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="adress",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personnel",
            name="cin",
            field=models.ImageField(
                blank=True, default="images/avatar.jpg", null=True, upload_to="images/"
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="cv",
            field=models.ImageField(
                blank=True, default="images/avatar.jpg", null=True, upload_to="images/"
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="situation",
            field=models.CharField(
                choices=[
                    ("celibataire", "celibataire"),
                    ("marié", "marié"),
                    ("veuf", "veuf"),
                ],
                default="celibataire",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="centre",
            field=models.CharField(
                choices=[
                    ("Antananarivo", "Antananarivo"),
                    ("Andakana", "Andakana"),
                    ("Ankaraobato", "Ankaraobato"),
                    ("Manakara", "Manakara"),
                ],
                default="Antananarivo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="section",
            field=models.CharField(
                choices=[
                    ("multimedia", "multimedia"),
                    ("cheick", "cheick"),
                    ("administration", "administration"),
                    ("rvs", "rvs"),
                    ("securite", "securite"),
                    ("jardinier", "jardinier"),
                    ("technicien", "technicien"),
                    ("cuisine", "cuisine"),
                    ("propreté", "propreté"),
                    ("madressat", "madressat"),
                    ("construction", "construction"),
                    ("transport", "transport"),
                ],
                default="multimedia",
                max_length=50,
            ),
        ),
    ]
