# Generated by Django 5.0.1 on 2024-04-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_personnel_adress_personnel_cin_personnel_cv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="designation",
            field=models.CharField(
                choices=[
                    ("Universite", "Universite"),
                    ("Jeune", "Jeune"),
                    ("Petit", "Petit"),
                ],
                default="Jeunes",
                max_length=100,
            ),
        ),
    ]
