# Generated by Django 5.0.1 on 2024-04-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_alter_etudiant_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="batch",
            field=models.CharField(
                choices=[
                    ("CP1", "CP1"),
                    ("CP2", "CP2"),
                    ("CP3", "CP3"),
                    ("CM1", "CM1"),
                    ("CM2", "CM2"),
                    ("6eme", "6eme"),
                    ("5eme", "5eme"),
                    ("4eme", "4eme"),
                    ("3eme", "3eme"),
                    ("2nd", "2nd"),
                    ("1ere", "1ere"),
                    ("Terminal", "Terminal"),
                    ("1ere annee", "1ere annee"),
                    ("2eme annee", "2eme annee"),
                    ("3eme annee", "3eme annee"),
                    ("4eme annee", "4eme annee"),
                    ("5eme annee", "5eme annee"),
                    ("6eme annee", "6eme annee"),
                ],
                default="1 ere annee",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="notes",
            name="designation",
            field=models.CharField(
                choices=[
                    ("Universite", "Universite"),
                    ("Jeune", "Jeune"),
                    ("Petit", "Petit"),
                ],
                default="Jeunes",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="notes",
            name="fillier",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
