# Generated by Django 5.0.1 on 2024-04-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_notes_batch_notes_designation_notes_fillier"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="institution",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
