# Generated by Django 5.0.1 on 2024-04-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_notes_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="batch",
            field=models.CharField(
                choices=[
                    ("CP1", "CP1"),
                    ("CP2", "CP2"),
                    ("CP3", "CP3"),
                    ("CM1", "CM1"),
                    ("CM2", "CM2"),
                    ("6eme", "6eme"),
                    ("5eme", "5eme"),
                    ("4eme", "4eme"),
                    ("3eme", "3eme"),
                    ("2nd", "2nd"),
                    ("1ere", "1ere"),
                    ("Terminal", "Terminal"),
                    ("1ere annee", "1ere annee"),
                    ("2eme annee", "2eme annee"),
                    ("3eme annee", "3eme annee"),
                    ("4eme annee", "4eme annee"),
                    ("5eme annee", "5eme annee"),
                    ("6eme annee", "6eme annee"),
                ],
                default="1ere annee",
                max_length=100,
            ),
        ),
    ]
