# Generated by Django 5.0.1 on 2024-04-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_alter_notes_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="designation",
            field=models.CharField(
                choices=[
                    ("Universite", "Universite"),
                    ("Jeune", "Jeune"),
                    ("Petit", "Petit"),
                ],
                default="Jeune",
                max_length=100,
            ),
        ),
    ]
