# Generated by Django 5.0.1 on 2024-05-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0032_alter_notes_designation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orphelin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("etudiantid", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "M"), ("F", "F")], default="M", max_length=4
                    ),
                ),
                ("name_mere", models.CharField(blank=True, max_length=100, null=True)),
                ("telephone_mere", models.IntegerField(blank=True, null=True)),
                (
                    "imageprofile",
                    models.ImageField(
                        blank=True,
                        default="images/avatar.jpg",
                        null=True,
                        upload_to="images/",
                    ),
                ),
                ("institution", models.CharField(max_length=100)),
                ("ville", models.CharField(max_length=100)),
                (
                    "batch",
                    models.CharField(
                        choices=[
                            ("CP1", "CP1"),
                            ("CP2", "CP2"),
                            ("CP3", "CP3"),
                            ("CM1", "CM1"),
                            ("CM2", "CM2"),
                            ("6eme", "6eme"),
                            ("5eme", "5eme"),
                            ("4eme", "4eme"),
                            ("3eme", "3eme"),
                            ("2nd", "2nd"),
                            ("1ere", "1ere"),
                            ("Terminal", "Terminal"),
                        ],
                        default="CP1",
                        max_length=100,
                    ),
                ),
                (
                    "centre",
                    models.CharField(
                        choices=[
                            ("Antananarivo", "Antananarivo"),
                            ("Manakara", "Manakara"),
                        ],
                        default="Antananarivo",
                        max_length=100,
                    ),
                ),
                ("date_entre", models.DateField(blank=True, null=True)),
                ("date_sortie", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="batch",
            field=models.CharField(
                choices=[
                    ("CP1", "CP1"),
                    ("CP2", "CP2"),
                    ("CP3", "CP3"),
                    ("CM1", "CM1"),
                    ("CM2", "CM2"),
                    ("6eme", "6eme"),
                    ("5eme", "5eme"),
                    ("4eme", "4eme"),
                    ("3eme", "3eme"),
                    ("2nd", "2nd"),
                    ("1ere", "1ere"),
                    ("Terminal", "Terminal"),
                    ("1ere annee", "1ere annee"),
                    ("2eme annee", "2eme annee"),
                    ("3eme annee", "3eme annee"),
                    ("4eme annee", "4eme annee"),
                    ("5eme annee", "5eme annee"),
                    ("6eme annee", "6eme annee"),
                ],
                default="1ere annee",
                max_length=100,
            ),
        ),
    ]
