# Generated by Django 5.0.1 on 2024-05-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0034_alter_etudiant_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierupload",
            name="etudiantid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dossier",
                to="main.etudiant",
            ),
        ),
        migrations.AlterField(
            model_name="dossierupload",
            name="namefile",
            field=models.CharField(default="Dossier", max_length=50),
        ),
    ]
