# Generated by Django 5.0.1 on 2024-05-27 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0035_alter_dossierupload_etudiantid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="etudiantid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="main.etudiant",
            ),
        ),
    ]
