# Generated by Django 5.0.1 on 2024-05-27 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0036_alter_notes_etudiantid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notes",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="notes",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="notes",
            name="fillier",
        ),
        migrations.RemoveField(
            model_name="notes",
            name="institution",
        ),
    ]
