# Generated by Django 5.0.1 on 2024-05-27 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0037_remove_notes_batch_remove_notes_designation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notes",
            old_name="imageprofile",
            new_name="notesimage",
        ),
    ]
