# Generated by Django 5.0.1 on 2024-05-27 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0038_rename_imageprofile_notes_notesimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notes",
            name="name",
        ),
    ]
