# Generated by Django 5.0.1 on 2024-05-27 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0039_remove_notes_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personnel",
            name="cin",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="cv",
        ),
    ]
