# Generated by Django 5.0.1 on 2024-05-27 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0040_remove_personnel_cin_remove_personnel_cv"),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierPersonnel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("namefile", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="dossier/")),
                (
                    "personnelid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.personnel",
                    ),
                ),
            ],
        ),
    ]
