# Generated by Django 5.0.1 on 2024-05-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0041_dossierpersonnel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="averissement",
            name="name",
        ),
        migrations.AlterField(
            model_name="averissement",
            name="etudiantid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.etudiant",
            ),
        ),
    ]
