# Generated by Django 5.0.1 on 2024-05-28 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0042_remove_averissement_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orphelin",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="centre",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="date_entre",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="date_naissance",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="date_sortie",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="imageprofile",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="name",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="name_mere",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="telephone_mere",
        ),
        migrations.RemoveField(
            model_name="orphelin",
            name="ville",
        ),
        migrations.AlterField(
            model_name="orphelin",
            name="etudiantid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orphelin",
                to="main.etudiant",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
