# Generated by Django 5.0.1 on 2024-06-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0043_remove_orphelin_batch_remove_orphelin_centre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="madrassah",
            name="telephone",
        ),
        migrations.AddField(
            model_name="madrassah",
            name="class_academic",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="madrassah",
            name="class_madressah",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="madrassah",
            name="parent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="madrassah",
            name="adress",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="madrassah",
            name="centre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Antananarivo", "Antananarivo"),
                    ("Ankaraobato", "Ankaraobato"),
                    ("Manakara", "Manakara"),
                    ("Andakana", "Andakana"),
                    ("Abarambamby", "Abarambamby"),
                    ("Andoarano", "Andoarano"),
                    ("Ambolonaondry", "Ambolonaondry"),
                    ("Limit-Est", "Limit-Est"),
                    ("Limit-Ouest", "Limit-Ouest"),
                    ("Analabe Manakara", "Analabe Manakara"),
                ],
                default="Antananarivo",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="madrassah",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
