# Generated by Django 5.0.1 on 2024-06-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0044_remove_madrassah_telephone_madrassah_class_academic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="madrassah",
            name="age",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
