# Generated by Django 5.0.1 on 2024-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0045_alter_madrassah_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="telephone_mere",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
