# Generated by Django 5.0.1 on 2024-06-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0046_alter_etudiant_telephone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="designation",
            field=models.CharField(
                choices=[
                    ("Universite", "Universite"),
                    ("Jeune", "Jeune"),
                    ("Petit", "Petit"),
                    ("Orphelinat", "Orphelinat"),
                ],
                default="Jeune",
                max_length=100,
            ),
        ),
    ]
