# Generated by Django 5.0.1 on 2024-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0047_alter_etudiant_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="centre",
            field=models.CharField(
                choices=[
                    ("Antananarivo", "Antananarivo"),
                    ("Manakara", "Manakara"),
                    ("Andakana", "Andakana"),
                    ("Sakoana", "Sakoana"),
                ],
                default="Antananarivo",
                max_length=100,
            ),
        ),
    ]
