# Generated by Django 5.0.1 on 2024-06-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0048_alter_etudiant_centre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="batch",
            field=models.CharField(
                choices=[
                    ("PS", "PS"),
                    ("MS", "MS"),
                    ("GS", "GS"),
                    ("CP", "CP"),
                    ("CE1", "CE1"),
                    ("CM1", "CM1"),
                    ("CM2", "CM2"),
                    ("6eme", "6eme"),
                    ("5eme", "5eme"),
                    ("4eme", "4eme"),
                    ("3eme", "3eme"),
                    ("2nd", "2nd"),
                    ("1ere", "1ere"),
                    ("Terminal", "Terminal"),
                    ("1ere annee", "1ere annee"),
                    ("2eme annee", "2eme annee"),
                    ("3eme annee", "3eme annee"),
                    ("4eme annee", "4eme annee"),
                    ("5eme annee", "5eme annee"),
                    ("6eme annee", "6eme annee"),
                ],
                default="1ere annee",
                max_length=100,
            ),
        ),
    ]
