# Generated by Django 5.0.1 on 2024-06-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0050_alter_etudiant_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presence",
            name="etudiantid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.etudiant",
            ),
        ),
    ]
