# Generated by Django 5.0.1 on 2024-07-01 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0051_alter_presence_etudiantid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="presence",
            name="name",
        ),
    ]
