# Generated by Django 5.0.1 on 2024-07-25 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0052_remove_presence_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orphelin",
            name="etudiantid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orphelin",
                to="main.etudiant",
            ),
        ),
    ]
