# Generated by Django 5.0.1 on 2024-07-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0053_alter_orphelin_etudiantid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="section",
            field=models.CharField(
                choices=[
                    ("multimedia", "multimedia"),
                    ("cheick", "cheick"),
                    ("administration", "administration"),
                    ("rvs", "rvs"),
                    ("securite", "securite"),
                    ("jardinier", "jardinier"),
                    ("technicien", "technicien"),
                    ("cuisine", "cuisine"),
                    ("propreté", "propreté"),
                    ("madressat", "madressat"),
                    ("construction", "construction"),
                    ("transport", "transport"),
                    ("dispensaire", "dispensaire"),
                ],
                default="multimedia",
                max_length=50,
            ),
        ),
    ]
