# Generated by Django 3.2.3 on 2024-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_personnel_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='centre',
            field=models.CharField(choices=[('Antananarivo', 'Antananarivo'), ('Ankarobato', 'Ankarobato'), ('Manakara', 'Manakara'), ('Andakana', 'Andakana'), ('Sakoana', 'Sakoana')], default='Antananarivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='designation',
            field=models.CharField(choices=[('Universite', 'Universite'), ('Jeune', 'Jeune'), ('Petit', 'Petit'), ('crashcourse', 'crashcourse')], default='Jeune', max_length=100),
        ),
    ]
