# Generated by Django 5.0.1 on 2024-08-02 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0055_auto_20240729_0718"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etudiant",
            old_name="name",
            new_name="nom",
        ),
    ]
