# Generated by Django 5.0.1 on 2024-08-02 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0056_rename_name_etudiant_nom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="averissement",
            old_name="etudiantid",
            new_name="identifiant",
        ),
        migrations.RenameField(
            model_name="dossierupload",
            old_name="etudiantid",
            new_name="identifiant",
        ),
        migrations.RenameField(
            model_name="etudiant",
            old_name="etudiantid",
            new_name="identifiant",
        ),
        migrations.RenameField(
            model_name="notes",
            old_name="etudiantid",
            new_name="identifiant",
        ),
        migrations.RenameField(
            model_name="orphelin",
            old_name="etudiantid",
            new_name="identifiant",
        ),
        migrations.RenameField(
            model_name="presence",
            old_name="etudiantid",
            new_name="identifiant",
        ),
    ]
