# Generated by Django 5.0.1 on 2024-08-02 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0057_rename_etudiantid_averissement_identifiant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etudiant",
            old_name="name_mere",
            new_name="nom_mere",
        ),
        migrations.RenameField(
            model_name="etudiant",
            old_name="name_pere",
            new_name="nom_pere",
        ),
    ]
