# Generated by Django 5.0.1 on 2024-08-02 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0058_rename_name_mere_etudiant_nom_mere_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etudiant",
            old_name="batch",
            new_name="Class",
        ),
    ]
