# Generated by Django 5.0.1 on 2024-08-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0059_rename_batch_etudiant_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="centre",
            field=models.CharField(
                choices=[
                    ("Antaniavo", "Antaniavo"),
                    ("Ankarobato", "Ankarobato"),
                    ("Manakara", "Manakara"),
                    ("Andakana", "Andakana"),
                    ("Sakoana", "Sakoana"),
                ],
                default="Antaniavo",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="jamat",
            name="centre",
            field=models.CharField(
                choices=[("Antaniano", "Antaniano"), ("Manakara", "Manakara")],
                default="Antaniano",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="madrassah",
            name="centre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Antaniano", "Antaniano"),
                    ("Ankaraobato", "Ankaraobato"),
                    ("Manakara", "Manakara"),
                    ("Andakana", "Andakana"),
                    ("Abarambamby", "Abarambamby"),
                    ("Andoarano", "Andoarano"),
                    ("Ambolonaondry", "Ambolonaondry"),
                    ("Limit-Est", "Limit-Est"),
                    ("Limit-Ouest", "Limit-Ouest"),
                    ("Analabe Manakara", "Analabe Manakara"),
                ],
                default="Antaniano",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="centre",
            field=models.CharField(
                choices=[
                    ("Antaniano", "Antaniano"),
                    ("Andakana", "Andakana"),
                    ("Ankaraobato", "Ankaraobato"),
                    ("Manakara", "Manakara"),
                ],
                default="Antaniano",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="centre",
            field=models.CharField(
                choices=[("Antaniano", "Antaniano"), ("Manakara", "Manakara")],
                default="Antaniano",
                max_length=20,
            ),
        ),
    ]
