# Generated by Django 5.0.1 on 2024-08-02 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0060_alter_etudiant_centre_alter_jamat_centre_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jamat",
            old_name="name",
            new_name="nom",
        ),
        migrations.RenameField(
            model_name="madrassah",
            old_name="name",
            new_name="nom",
        ),
        migrations.RenameField(
            model_name="personnel",
            old_name="name",
            new_name="nom",
        ),
    ]
