# Generated by Django 5.0.1 on 2024-08-02 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0061_rename_name_jamat_nom_rename_name_madrassah_nom_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dossierpersonnel",
            old_name="personnelid",
            new_name="identifiant",
        ),
        migrations.RenameField(
            model_name="personnel",
            old_name="personnelid",
            new_name="identifiant",
        ),
    ]
