# Generated by Django 5.0.1 on 2024-08-02 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0062_rename_personnelid_dossierpersonnel_identifiant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etudiant",
            old_name="sex",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="jamat",
            old_name="sex",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="madrassah",
            old_name="sex",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="personnel",
            old_name="sex",
            new_name="genre",
        ),
    ]
