# Generated by Django 5.0.1 on 2024-08-02 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0063_rename_sex_etudiant_genre_rename_sex_jamat_genre_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notes",
            old_name="year",
            new_name="annee",
        ),
    ]
