# Generated by Django 3.2.3 on 2024-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_rename_year_notes_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='moyen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
