# Generated by Django 3.2.3 on 2024-09-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_notes_moyen'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('S2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('S3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rang', models.CharField(blank=True, max_length=10, null=True)),
                ('decision', models.CharField(blank=True, choices=[('Admis', 'Admis'), ('Repechage', 'Repechage'), ('Redouble', 'Redouble'), ('Passable', 'Passable'), ('Assez-bien', 'Assez-bien'), ('Bien', 'Bien'), ('Tres bien', 'Tres bien')], default='Admis', max_length=11, null=True)),
                ('examreussite', models.CharField(blank=True, choices=[('CEPE', 'CEPE'), ('BEPC', 'BEPC'), ('BAC', 'BAC')], max_length=10, null=True)),
                ('notesimage', models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='notes/')),
                ('etudiantid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notesetudiant', to='main.etudiant')),
            ],
        ),
    ]
