# Generated by Django 3.2.3 on 2024-09-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_noteetudiant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteetudiant',
            old_name='year',
            new_name='annee',
        ),
        migrations.RenameField(
            model_name='noteetudiant',
            old_name='etudiantid',
            new_name='identifiant',
        ),
    ]
