# Generated by Django 3.2.3 on 2024-09-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20240926_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteetudiant',
            name='notesimage',
            field=models.FileField(blank=True, default='images/avatar.jpg', null=True, upload_to='notes/'),
        ),
    ]
