# Generated by Django 3.2.3 on 2024-10-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_noteetudiant_notesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphelin',
            name='acte_de_décé',
            field=models.FileField(blank=True, null=True, upload_to='actes/'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='décédé',
            field=models.CharField(blank=True, choices=[('mère', 'mère'), ('père', 'père')], default='père', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='designation',
            field=models.CharField(choices=[('Universite', 'Universite'), ('Jeune', 'Jeune'), ('Petit', 'Petit'), ('crashcourse', 'crashcourse'), ('internat', 'internat'), ('dine', 'dine')], default='Jeune', max_length=100),
        ),
    ]
