# Generated by Django 3.2.3 on 2024-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20241003_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphelin',
            name='décédé',
            field=models.CharField(blank=True, choices=[('mère', 'mère'), ('père', 'père')], max_length=50, null=True),
        ),
    ]
