# Generated by Django 3.2.3 on 2024-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_orphelin_décédé'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(verbose_name='Date de Naissance'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='designation',
            field=models.CharField(choices=[('Universite', 'Universite'), ('Jeune', 'Jeune'), ('Petit', 'Petit'), ('crashcourse', 'crashcourse'), ('internat', 'internat'), ('dine', 'dine'), ('Bachelor Dine', 'Bachelor Dine'), ('Bachelor Université', 'Bachelor Université')], default='Jeune', max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du mère'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du père'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='annee',
            field=models.CharField(max_length=10, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='moyen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Moyen'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='semestre',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='S1', max_length=10, null=True, verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='acte_de_décé',
            field=models.FileField(blank=True, null=True, upload_to='actes/', verbose_name='Acte de décé'),
        ),
    ]
