# Generated by Django 3.2.3 on 2024-11-01 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20241007_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orphelin',
            name='décédé',
        ),
        migrations.AddField(
            model_name='orphelin',
            name='orphelin_de',
            field=models.CharField(blank=True, choices=[('mère', 'mère'), ('père', 'père'), ('non orphelin', 'non orphelin')], max_length=50, null=True, verbose_name='Orphelin de'),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='identifiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orphelin', to='main.etudiant', unique=True),
        ),
    ]
