# Generated by Django 3.2.3 on 2024-11-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20241101_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orphelin',
            old_name='orphelin_de',
            new_name='décedé',
        ),
    ]
