# Generated by Django 3.2.3 on 2024-11-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_alter_orphelin_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphelin',
            name='décedé',
            field=models.CharField(blank=True, choices=[('mère', 'mère'), ('père', 'père'), ('non orphelin', 'non orphelin')], max_length=50, null=True, verbose_name='Orphelin'),
        ),
    ]
