# Generated by Django 3.2.3 on 2024-11-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_alter_orphelin_décedé'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphelin',
            name='identifiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orphelin', to='main.etudiant', verbose_name='Identifiant'),
        ),
    ]
