# Generated by Django 5.1.2 on 2025-01-27 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_alter_orphelin_identifiant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierpersonnel',
            name='identifiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.personnel'),
        ),
        migrations.AlterField(
            model_name='dossierupload',
            name='identifiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='main.etudiant'),
        ),
        migrations.AlterField(
            model_name='noteetudiant',
            name='identifiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notesetudiant', to='main.etudiant'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='identifiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.etudiant'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='identifiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etudiant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Avertissement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('raison', models.CharField(max_length=100, null=True)),
                ('identifiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etudiant')),
            ],
        ),
        migrations.DeleteModel(
            name='Averissement',
        ),
    ]
