# Generated by Django 5.1.2 on 2025-02-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_alter_dossierpersonnel_identifiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteetudiant',
            name='rang',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
