# Generated by Django 5.1.2 on 2025-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_alter_noteetudiant_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteetudiant',
            name='orphelin',
            field=models.CharField(blank=True, choices=[('Orphelin', 'Orphelin'), ('Etudiant', 'Etudiant')], default='Etudiant', max_length=11, null=True),
        ),
    ]
