# Generated by Django 5.1.2 on 2025-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_noteetudiant_orphelin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphelin',
            name='décedé',
            field=models.CharField(blank=True, choices=[('mère', 'mère'), ('père', 'père'), ('Pas de parent', 'Pas de parent'), ('non orphelin', 'non orphelin')], max_length=50, null=True, verbose_name='Orphelin'),
        ),
    ]
