# Generated by Django 5.2.1 on 2025-06-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_alter_orphelin_décedé'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['nom'], 'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnel'},
        ),
        migrations.AddField(
            model_name='personnel',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Contact d'urgence - Nom"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Contact d'urgence - Téléphone"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='statut_matrimonial',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('veuf', 'Veuf/Veuve'), ('divorce', 'Divorcé(e)')], default='celibataire', max_length=50, verbose_name='Statut matrimonial'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='centre',
            field=models.CharField(choices=[('Antaniavo', 'Antaniavo'), ('Andakana', 'Andakana'), ('Ankarobato', 'Ankarobato'), ('Manakara', 'Manakara'), ('Sakoana', 'Sakoana')], default='Antaniavo', max_length=20, verbose_name='Centre'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=5, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='identifiant',
            field=models.CharField(max_length=100, unique=True, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='imageprofile',
            field=models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='section',
            field=models.CharField(choices=[('multimedia', 'Multimédia'), ('cheick', 'Cheick'), ('administration', 'Administration'), ('rvs', 'RVS'), ('securite', 'Sécurité'), ('jardinier', 'Jardinier'), ('technicien', 'Technicien'), ('cuisine', 'Cuisine'), ('proprete', 'Propreté'), ('madressat', 'Madressat'), ('construction', 'Construction'), ('transport', 'Transport'), ('dispensaire', 'Dispensaire'), ('maintenance', 'Maintenance'), ('comptabilite', 'Comptabilité')], default='multimedia', max_length=50, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='situation',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('En congé', 'En congé'), ('Suspendu', 'Suspendu'), ('Retraité', 'Retraité')], default='Actif', max_length=50, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='travail',
            field=models.CharField(choices=[('Enseignant', 'Enseignant'), ('Administrateur', 'Administrateur'), ('Technicien', 'Technicien'), ('Superviseur', 'Superviseur'), ('Coordinateur', 'Coordinateur'), ('Responsable', 'Responsable'), ('Assistant', 'Assistant'), ('Consultant', 'Consultant'), ('Support', 'Support'), ('Maintenance', 'Maintenance'), ('Gardien', 'Gardien'), ('Chauffeur', 'Chauffeur'), ('Cuisinier', 'Cuisinier'), ('Jardinier', 'Jardinier'), ('Nettoyage', 'Nettoyage')], default='Assistant', max_length=100, verbose_name='Type de travail'),
        ),
    ]
