# Generated by Django 5.2.1 on 2025-06-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_alter_personnel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jamat',
            old_name='job',
            new_name='travail',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='contact_urgence_nom',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='contact_urgence_telephone',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='salaire',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='statut_matrimonial',
        ),
        migrations.AlterField(
            model_name='jamat',
            name='centre',
            field=models.CharField(choices=[('Antaniavo', 'Antaniavo'), ('Ankarobato', 'Ankarobato'), ('Manakara', 'Manakara'), ('Andakana', 'Andakana'), ('Sakoana', 'Sakoana')], default='Antaniano', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='situation',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('veuf', 'Veuf/Veuve'), ('divorce', 'Divorcé(e)')], default='celibataire', max_length=50, verbose_name='Statut matrimonial'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['identifiant'], name='main_person_identif_d4997b_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['nom'], name='main_person_nom_be1c27_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['section'], name='main_person_section_5eb3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['centre'], name='main_person_centre_ef10a1_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['situation'], name='main_person_situati_bd0cd7_idx'),
        ),
    ]
