# Generated by Django 5.2.1 on 2025-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_rename_job_jamat_travail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='identifiant',
            field=models.CharField(max_length=100, verbose_name='Identifiant'),
        ),
    ]
