# Generated by Django 5.2.1 on 2025-06-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_personnel_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='identifiant',
            field=models.CharField(max_length=100, unique=True, verbose_name='Identifiant'),
        ),
    ]
