# Generated by Django 5.2.1 on 2025-06-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_alter_personnel_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamat',
            name='telephone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
