# Generated by Django 5.2.1 on 2025-06-05 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_alter_jamat_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=5)),
                ('telephone', models.CharField(blank=True, null=True)),
                ('adress', models.CharField(blank=True, max_length=100, null=True)),
                ('imageprofile', models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/')),
                ('date_pension', models.DateField(blank=True, null=True)),
                ('pension', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cause', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_enfants', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('jamat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jamat')),
            ],
        ),
        migrations.CreateModel(
            name='DossierPension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namefile', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='dossier/')),
                ('pension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pension')),
            ],
        ),
    ]
