# Generated by Django 5.2.1 on 2025-06-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_pension_dossierpension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pension',
            name='jamat',
        ),
    ]
