# Generated by Django 5.2.1 on 2025-06-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_remove_pension_jamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pension',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='pension',
            name='cause',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cause'),
        ),
        migrations.AlterField(
            model_name='pension',
            name='nombre_enfants',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'enfants"),
        ),
        migrations.AlterField(
            model_name='pension',
            name='pension',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pension (Ar)'),
        ),
        migrations.CreateModel(
            name='Paiementpension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('Payé', 'Payé'), ('Avance', 'Avance')], default='Payé', max_length=100)),
                ('pension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pension')),
            ],
        ),
    ]
