# Generated by Django 5.2.1 on 2025-06-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_alter_pension_age_alter_pension_cause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementpension',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant (Ar)'),
        ),
    ]
