# Generated by Django 5.2.1 on 2025-07-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_alter_paiementpension_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('Sortant', 'Sortant')], default='Actif', max_length=100),
        ),
    ]
