# Generated by Django 5.2.1 on 2025-07-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_etudiant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cimitiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('genre', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=5, verbose_name='Genre')),
                ('imageprofile', models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/', verbose_name='Photo de profil')),
                ('date_deces', models.DateField(blank=True, null=True, verbose_name='Date de décès')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_deces', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de décès')),
                ('famille', models.CharField(blank=True, max_length=100, null=True, verbose_name='Famille')),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse de la Famille')),
                ('telephone', models.CharField(blank=True, null=True, verbose_name='Téléphone de la Famille')),
            ],
        ),
        migrations.CreateModel(
            name='DossierCimitiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namefile', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='dossier_cimitiere/')),
                ('cimitiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cimitiere')),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
