# Generated by Django 5.2.1 on 2025-07-11 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_cimitiere_dossiercimitiere_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteOrphelin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.noteetudiant')),
            ],
        ),
    ]
