# Generated by Django 5.2.1 on 2025-07-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_noteorphelin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elite', to='main.etudiant', verbose_name='Identifiant')),
            ],
        ),
        migrations.CreateModel(
            name='NoteElite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.noteetudiant')),
            ],
        ),
    ]
