# Generated by Django 5.2.1 on 2025-07-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_elite_noteelite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='designation',
            field=models.CharField(choices=[('Universite', 'Universite'), ('Jeune', 'Jeune'), ('Elite', 'Elite'), ('Petit', 'Petit'), ('crashcourse', 'crashcourse'), ('internat', 'internat'), ('dine', 'dine'), ('Bachelor Dine', 'Bachelor Dine'), ('Bachelor Université', 'Bachelor Université')], default='Jeune', max_length=100),
        ),
    ]
