# Generated by Django 5.2.1 on 2025-07-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_alter_etudiant_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteetudiant',
            name='orphelin',
            field=models.CharField(blank=True, choices=[('Orphelin', 'Orphelin'), ('Etudiant', 'Etudiant'), ('Elite', 'Elite')], default='Etudiant', max_length=11, null=True),
        ),
        migrations.DeleteModel(
            name='NoteOrphelin',
        ),
    ]
