# Generated by Django 5.2.1 on 2025-08-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_alter_noteetudiant_orphelin_delete_noteorphelin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueEtudiant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('raison', models.TextField(blank=True, null=True)),
                ('identifiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='main.etudiant', verbose_name='Identifiant')),
            ],
        ),
    ]
