# Generated by Django 5.2.1 on 2025-08-11 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_historiqueetudiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='email',
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('universite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etudiant', verbose_name='Identifiant')),
            ],
        ),
    ]
