# Generated by Django 5.2.1 on 2025-08-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_remove_etudiant_email_universite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=4)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('nom_pere', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du père')),
                ('nom_mere', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la mère')),
                ('placement_type', models.CharField(choices=[('Orphelinat', 'Orphelinat'), ('Université', 'Université'), ('Etudiant', 'Etudiant'), ('Autre', 'Autre')], default='Autre', max_length=20, verbose_name='Type de placement')),
                ('poste_actuel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste actuel')),
                ('entreprise', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entreprise')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('adresse_actuelle', models.TextField(blank=True, null=True, verbose_name='Adresse actuelle')),
                ('ville_actuelle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville actuelle')),
                ('status', models.CharField(choices=[('Embauche', 'Embauche'), ('Non Embauche', 'Non Embauche')], default='Non Embauche', max_length=20)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sortant', to='main.etudiant', verbose_name='Étudiant enregistré')),
            ],
            options={
                'verbose_name': 'Sortant',
                'verbose_name_plural': 'Sortants',
            },
        ),
    ]
