# Generated by Django 5.2.1 on 2025-08-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_sortant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortant',
            name='imageprofile',
            field=models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/'),
        ),
    ]
