# Generated by Django 5.2.1 on 2025-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_sortant_imageprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortant',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='nom_mere',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='nom_pere',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='ville_actuelle',
        ),
        migrations.AddField(
            model_name='sortant',
            name='statut_matrimonial',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié'), ('Divorcé', 'Divorcé'), ('Veuf', 'Veuf')], default='Célibataire', max_length=100, verbose_name='Statut matrimonial'),
        ),
    ]
