# Generated by Django 5.2.1 on 2025-08-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_remove_sortant_etudiant_remove_sortant_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortant',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sortant', to='main.etudiant', verbose_name='Étudiant enregistré'),
        ),
        migrations.AddField(
            model_name='sortant',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=4),
        ),
        migrations.AddField(
            model_name='sortant',
            name='nom',
            field=models.CharField(default='', max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='sortant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='sortant',
            name='ville_actuelle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville actuelle'),
        ),
    ]
