# Generated by Django 5.2.1 on 2025-08-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_sortant_etudiant_sortant_genre_sortant_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Naissance'),
        ),
    ]
