# Generated by Django 5.2.1 on 2025-09-04 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_alter_etudiant_date_naissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortant',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='imageprofile',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='sortant',
            name='ville_actuelle',
        ),
        migrations.AddField(
            model_name='sortant',
            name='lieu_travail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de travail'),
        ),
        migrations.AddField(
            model_name='sortant',
            name='sortant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etudiant', verbose_name='Identifiant'),
        ),
    ]
