# Generated by Django 5.2.1 on 2025-09-24 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_remove_sortant_date_naissance_remove_sortant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cimitiere',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de la Famille'),
        ),
        migrations.AlterField(
            model_name='jamat',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pension',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archive_type', models.CharField(choices=[('Orphelin', 'Orphelin'), ('Sortant', 'Sortant'), ('Université', 'Université'), ('crashcourses', 'crashcourses'), ('Elite', 'Elite'), ('Petit', 'Petit'), ('Jeune', 'Jeune'), ('Bachelor Dine', 'Bachelor Dine'), ('Bachelor Université', 'Bachelor Université'), ('internat', 'internat'), ('dine', 'dine'), ('Autre', 'Autre')], default='Autre', max_length=20, verbose_name="Type d'archive")),
                ('raison', models.CharField(choices=[('Renvoyé', 'Renvoyé'), ('Démission', 'Démission'), ('Décédé', 'Décédé'), ('Sortant', 'Sortant'), ('Autre', 'Autre')], default='Autre', max_length=20, verbose_name="Raison d'archive")),
                ('archive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etudiant', verbose_name='Identifiant')),
            ],
        ),
    ]
