# Generated by Django 5.2.1 on 2025-09-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_alter_cimitiere_telephone_alter_jamat_telephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pays', models.CharField(choices=[('India', 'India'), ('Irak', 'Irak'), ('Iran', 'Iran'), ('Maroc', 'Maroc'), ('Indonésie', 'Indonésie'), ('France', 'France'), ('Autre', 'Autre')], default='Autre', max_length=20, verbose_name='Pays')),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('duree_sejour', models.IntegerField(blank=True, null=True, verbose_name='Durée de séjour (année)')),
                ('international', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etudiant', verbose_name='Identifiant')),
            ],
        ),
    ]
