# Generated by Django 5.2.1 on 2025-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_international'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='designation',
            field=models.CharField(choices=[('Universite', 'Universite'), ('Jeune', 'Jeune'), ('Elite', 'Elite'), ('International', 'International'), ('Petit', 'Petit'), ('crashcourse', 'crashcourse'), ('internat', 'internat'), ('dine', 'dine'), ('Bachelor Dine', 'Bachelor Dine'), ('Bachelor Université', 'Bachelor Université')], default='Jeune', max_length=100),
        ),
    ]
