# Generated by Django 5.2.1 on 2026-01-15 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_alter_etudiant_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamat',
            name='conversion_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de conversion'),
        ),
        migrations.CreateModel(
            name='ArchiveJamat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archive_type', models.CharField(choices=[('Jamat', 'Jamat'), ('Autre', 'Autre')], default='Jamat', max_length=20, verbose_name="Type d'archive")),
                ('raison', models.CharField(choices=[('Renvoyé', 'Renvoyé'), ('Démission', 'Démission'), ('Décédé', 'Décédé'), ('Sortant', 'Sortant'), ('Autre', 'Autre')], default='Autre', max_length=20, verbose_name="Raison d'archive")),
                ('archived_at', models.DateField(auto_now_add=True, verbose_name="Date d'archive")),
                ('jamat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jamat', verbose_name='Jamat')),
            ],
        ),
    ]
