# Generated by Django 5.2.1 on 2026-01-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_jamat_conversion_year_archivejamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='identifiant',
            field=models.CharField(max_length=100, unique=True, verbose_name='matricule'),
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('raison', models.TextField(blank=True, null=True, verbose_name='Raison')),
                ('statut', models.CharField(choices=[('Maladie', 'Maladie'), ('Famille', 'Famille'), ('Congé', 'Congé'), ('Autre', 'Autre')], default='Congé', max_length=100, verbose_name='Type de congé')),
                ('identifiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.personnel', verbose_name='matricule')),
            ],
        ),
    ]
