# Generated by Django 5.2.1 on 2026-01-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_alter_personnel_identifiant_conge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterAlias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('main_center', models.CharField(choices=[('Antaniavo', 'Antaniavo'), ('Ankarobato', 'Ankarobato'), ('Manakara', 'Manakara'), ('Andakana', 'Andakana'), ('Sakoana', 'Sakoana')], max_length=100, verbose_name='Centre principal')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='Alias')),
            ],
            options={
                'verbose_name': 'Alias de Centre',
                'verbose_name_plural': 'Alias de Centres',
                'ordering': ['main_center', 'alias'],
            },
        ),
        migrations.AlterField(
            model_name='jamat',
            name='centre',
            field=models.CharField(choices=[('Antaniavo', 'Antaniavo'), ('Ankarobato', 'Ankarobato'), ('Manakara', 'Manakara'), ('Andakana', 'Andakana'), ('Sakoana', 'Sakoana')], default='Antaniavo', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='centre',
            field=models.CharField(choices=[('Antaniavo', 'Antaniavo'), ('Ankarobato', 'Ankarobato'), ('Manakara', 'Manakara'), ('Andakana', 'Andakana'), ('Sakoana', 'Sakoana')], default='Antaniavo', max_length=20, verbose_name='Centre'),
        ),
    ]
