# Generated by Django 5.2.1 on 2026-01-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_centeralias_alter_jamat_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='centre',
            field=models.CharField(default='Antaniavo', max_length=100),
        ),
        migrations.AlterField(
            model_name='jamat',
            name='centre',
            field=models.CharField(default='Antaniavo', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='centre',
            field=models.CharField(default='Antaniavo', max_length=100, verbose_name='Centre'),
        ),
    ]
