# Generated by Django 5.2.1 on 2026-02-06 06:33

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_alter_etudiant_centre_alter_jamat_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='centre',
            field=models.CharField(choices=main.models.get_centre_choices, default='Antaniavo', max_length=100),
        ),
        migrations.AlterField(
            model_name='jamat',
            name='centre',
            field=models.CharField(choices=[('Antaniavo', 'Antaniavo'), ('Ankarobato', 'Ankarobato'), ('Manakara', 'Manakara'), ('Andakana', 'Andakana'), ('Sakoana', 'Sakoana'), ('ANORONORO', 'ANORONORO'), ('AMBOLOSY', 'AMBOLOSY'), ('AMBARAMBABY', 'AMBARAMBABY'), ('AMBODINATO', 'AMBODINATO'), ('AMPITSONJOVA', 'AMPITSONJOVA'), ('ANDOHARANO', 'ANDOHARANO'), ('ANDRANOVATO', 'ANDRANOVATO'), ('AMBOLONAONDRY', 'AMBOLONAONDRY'), ('ANALANJIROFO', 'ANALANJIROFO'), ('AMBOROBE', 'AMBOROBE')], default='Antaniavo', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='centre',
            field=models.CharField(choices=main.models.get_centre_choices, default='Antaniavo', max_length=100, verbose_name='Centre'),
        ),
    ]
