# Generated by Django 4.2.28 on 2026-04-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0115_archivemadrassah"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="centre",
            field=models.CharField(
                choices=[
                    ("Andakana", "Andakana"),
                    ("Ankarobato", "Ankarobato"),
                    ("Antaniavo", "Antaniavo"),
                    ("Manakara", "Manakara"),
                    ("Manakara-Roshan Jamil", "Manakara-Roshan Jamil (Manakara)"),
                    ("Sakoana", "Sakoana"),
                    ("Sakoana Abdoul Moumin", "Sakoana Abdoul Moumin (Sakoana)"),
                    ("Sakoana-MRK", "Sakoana-MRK (Sakoana)"),
                ],
                default="Antaniavo",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="noteetudiant",
            name="rang",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="centre",
            field=models.CharField(
                choices=[
                    ("Andakana", "Andakana"),
                    ("Ankarobato", "Ankarobato"),
                    ("Antaniavo", "Antaniavo"),
                    ("Manakara", "Manakara"),
                    ("Manakara-Roshan Jamil", "Manakara-Roshan Jamil (Manakara)"),
                    ("Sakoana", "Sakoana"),
                    ("Sakoana Abdoul Moumin", "Sakoana Abdoul Moumin (Sakoana)"),
                    ("Sakoana-MRK", "Sakoana-MRK (Sakoana)"),
                ],
                default="Antaniavo",
                max_length=100,
                verbose_name="Centre",
            ),
        ),
        migrations.CreateModel(
            name="HistoriqueSanteEtudiant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "observation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observation / suivi santé"
                    ),
                ),
                (
                    "identifiant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_sante",
                        to="main.etudiant",
                        verbose_name="Identifiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique santé étudiant",
                "verbose_name_plural": "Historiques santé étudiants",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
