# Generated by Django 5.2.13 on 2026-04-10 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0116_historique_sante_etudiant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historiquesanteetudiant",
            options={},
        ),
        migrations.AddField(
            model_name="historiquesanteetudiant",
            name="raison",
            field=models.CharField(
                default="Autre", max_length=100, verbose_name="Raison"
            ),
        ),
        migrations.AlterField(
            model_name="historiquesanteetudiant",
            name="identifiant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.etudiant",
                verbose_name="Identifiant",
            ),
        ),
    ]
